### ISSUE TITLE
Clean2 files not generating

### ISSUE THREAD

**Issue by mafurst** [HetML/TRIPS#1]
Not all xml.clean files produce xml.clean2

**Comment by abhatia15** [comment]
yes, could you try and figure out why that is? May be look at the .xmls for which we are able to produce .clean2 and the ones for which we don't produce them. Do you see any consistent pattern? Look at the code (convert_cleaned_xmls_to_refinedxmls.py) too to make sure there isn't an error there which may be causing us to lose some data.

**Comment by mafurst** [comment]
I think the issue may stem from textstart and textend in the 87-92 line range. It seems that it can't always find an iterator with sent_text and throws an error. Below is an example of the error.
`File:
train-sentences.txt-154.xml
Type: <class 'UnboundLocalError'>
Error Arguments:
local variable 'textstart' referenced before assignment
 `

**Comment by abhatia15** [comment]
ok, thanks. See if you can fix it. You can look at the content in train-sentences.txt-154.xml and see how other files for which clean2 is created are different from it, it may help while trying to fix.
