### ISSUE TITLE
Clean files not loading

### ISSUE THREAD

**Issue by mafurst** [HetML/TRIPS#2]
.clean files aren't always created when running parse_trips_xml.py

**Comment by mafurst** [comment]
Pretty sure issue is due to .xml files not always having comments. Going to add better error logging in future patch to ensure.

**Comment by abhatia15** [comment]
The .clean files are not created if the original xml does not have an actual parse for an utterance (the content between the  < rdf:RDF > and </rdf:RDF> tags).
